services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        build: ./nginx
        ports:
            - "8091:80"
        depends_on:
            - php
            - mysql
        volumes:
            - ./src:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    php:
        image: php:7.4-fpm-alpine
        container_name: php
        build: .
        volumes:
            - ./src:/var/www/html
    mysql:
        image: mysql:latest
        container_name: mysql
        restart: unless-stopped
        volumes:
            - ./mysql_data:/var/lib/mysql
            - ./mysql/testing-db.sql:/docker-entrypoint-initdb.d/testing-db.sql
        environment:
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
        ports:
            - "4306:3306"